<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) by  (UBS Business Solutions UK) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:include schemaLocation="../AFFragments/WorkParties.xsd"/>
	<xs:element name="Card" type="CardType"/>
	<xs:element name="CardExisting" type="CardType"/>
	<xs:element name="CardMatrixMain" type="CardMatrixType"/>
	<xs:element name="CardMatrixSecond" type="CardMatrixType"/>
	<xs:element name="CardMatrixPartner" type="CardMatrixType"/>
	<xs:element name="CardMatrixSecondPartner" type="CardMatrixType"/>
	<xs:element name="CardAdditionalService" type="CardAdditionalServiceType"/>
	<xs:element name="CardHolder" type="CardHolderType"/>
	<xs:element name="CardHolderPartner" type="CardHolderType"/>
	<xs:element name="CardBank" type="CardBankType"/>
	<xs:element name="CardMailingAddress" type="CardAddressType"/>
	<xs:element name="CardInvoiceAddress" type="CardAddressType"/>
	<xs:element name="CardPartnerAddress" type="CardAddressType"/>
	<xs:element name="CardTraining" type="CardTrainingType"/>
	<xs:element name="CardEmployment" type="CardEmploymentType"/>
	<xs:element name="CardLegalRep" type="CardLegalRepType"/>
	<xs:element name="EmbossingLine" type="EmbossingLineType"/>
	<xs:complexType name="CardType">
		<xs:sequence>
			<xs:element name="FirstSixDigits" type="xs:string"/>
			<xs:element name="ProtectedNumber1" type="xs:string"/>
			<xs:element name="ProtectedNumber2" type="xs:string" minOccurs="0"/>
			<xs:element name="LastFourDigits" type="xs:string"/>
			<xs:element name="CardNumber" type="xs:string" minOccurs="0"/>
			<xs:element name="CardProduct" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CardMatrixType">
		<xs:sequence>
			<xs:element name="Brand" type="xs:string" minOccurs="0"/>
			<xs:element name="Design" type="xs:string" minOccurs="0"/>
			<xs:element name="Currency" type="xs:string" minOccurs="0"/>
			<xs:element name="SurchargePerMonth" type="xs:string" minOccurs="0"/>
			<xs:element name="MaxLimit" type="xs:decimal" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CardAdditionalServiceType">
		<xs:sequence>
			<xs:element name="KeyClubProgram" type="xs:string"/>
			<xs:element name="TravelInsurance" type="xs:string"/>
			<xs:element name="InsuranceStartDate" type="xs:date" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CardHolderType">
		<xs:complexContent>
			<xs:extension base="IndividualType">
				<xs:sequence>
					<xs:element name="CorrespondenceLanguage" type="xs:string" minOccurs="0"/>
					<xs:element name="PersonalCodeword" type="xs:string" minOccurs="0"/>
					<xs:element ref="GPN" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CardBankType">
		<xs:complexContent>
			<xs:extension base="BankType">
				<xs:sequence>
					<xs:element name="ContactPerson" type="xs:string"/>
					<xs:element name="AccountNo" type="xs:string"/>
					<xs:element name="ClearingNo" type="xs:string"/>
					<xs:element ref="IBAN"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CardAddressType">
		<xs:complexContent>
			<xs:extension base="IndividualType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CardTrainingType">
		<xs:sequence>
			<xs:element name="Training" type="xs:string"/>
			<xs:element name="StartDate" type="xs:date"/>
			<xs:element name="EducationalEstablishment" type="xs:string"/>
			<xs:element name="CompletionDate" type="xs:date"/>
			<xs:element name="PostalCodeCity" type="xs:string"/>
			<xs:element name="Fortune" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CardLegalRepType">
		<xs:complexContent>
			<xs:extension base="IndividualType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CardEmploymentType">
		<xs:sequence>
			<xs:element name="Profession" type="xs:string" minOccurs="0"/>
			<xs:element name="Employer" type="xs:string" minOccurs="0"/>
			<xs:element name="Sector" type="xs:string" minOccurs="0"/>
			<xs:element name="PostalCodeCity" type="xs:string" minOccurs="0"/>
			<xs:element name="ContractSituation" type="xs:string"/>
			<xs:element name="GrossAnnualIncome" type="xs:string"/>
			<xs:element name="Period" type="xs:string"/>
			<xs:element name="EndDateIfLimited" type="xs:date" minOccurs="0"/>
			<xs:element name="BusinessPhone" type="xs:string" minOccurs="0"/>
			<xs:element name="Fortune" type="xs:string" minOccurs="0"/>
			<xs:element ref="GPN" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EmbossingLineType">
		<xs:sequence>
			<xs:element name="EmbossingLineNames" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>