<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) by  (UBS Business Solutions UK) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Signature" type="SignatureType"/>
	<xs:element name="CardHolderSignature" type="SignatureType"/>
	<xs:element name="CardHolderPartnerSignature" type="SignatureType"/>
	<xs:element name="CardLegalRepSignature" type="SignatureType"/>
	<xs:element name="SignatureHKCA" type="SignatureHKCAType">
		<xs:annotation>
			<xs:documentation>signature / HR MA registration number</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="SignatureVerification" type="SignatureVerificationType">
		<xs:annotation>
			<xs:documentation>witness / verified against etc</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="SignatureHKCAType">
		<xs:annotation>
			<xs:documentation>signature / HR MA registration number</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element ref="Signature"/>
			<xs:element name="HKMARegistrationNo" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SignatureType">
		<xs:sequence>
			<xs:element name="Place" type="xs:string" minOccurs="0"/>
			<xs:element name="Name" type="xs:string" minOccurs="0"/>
			<xs:element name="Date" type="xs:date" minOccurs="0"/>
			<xs:element name="Role" type="xs:string" minOccurs="0"/>
			<xs:element name="OURef" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SignatureVerificationType">
		<xs:sequence>
			<xs:element name="Witnessed" type="xs:boolean" minOccurs="0"/>
			<xs:element name="VerifiedAgainsted" type="xs:boolean" minOccurs="0"/>
			<xs:element name="VerifiedAgainstSignatureSpecimen" type="xs:boolean" minOccurs="0"/>
			<xs:element name="VerifiedAgainstPassport" type="xs:boolean" minOccurs="0"/>
			<xs:element name="VerifiedAgainstExistingBR" type="xs:boolean" minOccurs="0"/>
			<xs:element name="VerifiedExistingBR" type="xs:string" minOccurs="0"/>
			<xs:element name="VerifiedAgainstAlternative" type="xs:boolean" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>