<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) by  (UBS Business Solutions UK) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="USPersonStatusDeclaration">
		<xs:annotation>
			<xs:documentation>US person declaration</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Is_US_Citizen" type="xs:string" minOccurs="0"/>
				<xs:element name="Is_Born_In_US" type="xs:string" minOccurs="0"/>
				<xs:element name="Is_US_GreenCard_Holder" type="xs:string" minOccurs="0"/>
				<xs:element name="Is_Resident_Of_US" type="xs:string" minOccurs="0"/>
				<xs:element name="Is_Domiciled_In_US" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>