//! PostgreSQL serialisation of a [`Dump`], ported verbatim from
//! `ajila-forms-conversion-engine/core/src/redacto/sql.rs`'s own quoting
//! rule.

use crate::rows::Dump;

const SCHEMA: &str = "app_redacto";

/// Quote a value as a PostgreSQL string literal.
///
/// Single quotes are always doubled. When the value contains a backslash,
/// tab, newline or carriage return, an escape-string literal `e'…'` is
/// emitted and those characters are written as `\\`, `\t`, `\n`, `\r` --
/// this keeps every `INSERT` on a single line and makes the dump
/// independent of the server's `standard_conforming_strings` setting.
pub fn sql_string(value: &str) -> String {
    let needs_escape = value.contains(['\\', '\t', '\n', '\r']);
    let mut out = String::with_capacity(value.len() + 8);
    if needs_escape {
        out.push('e');
    }
    out.push('\'');
    for ch in value.chars() {
        match ch {
            '\'' => out.push_str("''"),
            '\\' if needs_escape => out.push_str("\\\\"),
            '\t' if needs_escape => out.push_str("\\t"),
            '\n' if needs_escape => out.push_str("\\n"),
            '\r' if needs_escape => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
    out
}

fn insert(table: &str, columns: &str, values: &[String]) -> String {
    format!("INSERT INTO {SCHEMA}.{table} ({columns}) VALUES ({});\n", values.join(", "))
}

/// Serialise the dump as a PostgreSQL script: one transaction, tables in
/// foreign-key dependency order.
pub fn to_sql(dump: &Dump) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by u2s-mapper-redacto.\n");
    out.push_str("BEGIN;\n");

    out.push_str("\n-- assets\n");
    for row in &dump.assets {
        out.push_str(&insert(
            "assets",
            "id, created, asset_id, asset_type",
            &[
                sql_string(&row.id),
                sql_string(&row.created),
                sql_string(&row.asset_id),
                sql_string(row.asset_type.as_sql_literal()),
            ],
        ));
    }

    out.push_str("\n-- asset_version\n");
    for row in &dump.asset_versions {
        out.push_str(&insert(
            "asset_version",
            "id, created, language, version, status, content, asset_fk_id",
            &[
                sql_string(&row.id),
                sql_string(&row.created),
                sql_string(&row.language),
                row.version.to_string(),
                sql_string(row.status.as_sql_literal()),
                sql_string(&row.content),
                sql_string(&row.asset_fk_id),
            ],
        ));
    }

    out.push_str("\n-- documents\n");
    for row in &dump.documents {
        out.push_str(&insert(
            "documents",
            "id, created, document_id, form_path, configuration",
            &[
                sql_string(&row.id),
                sql_string(&row.created),
                sql_string(&row.document_id),
                sql_string(&row.form_path),
                sql_string(&row.configuration),
            ],
        ));
    }

    out.push_str("\n-- document_version\n");
    for row in &dump.document_versions {
        out.push_str(&insert(
            "document_version",
            "id, created, language, version, status, document_fk_id",
            &[
                sql_string(&row.id),
                sql_string(&row.created),
                sql_string(&row.language),
                row.version.to_string(),
                sql_string(row.status.as_sql_literal()),
                sql_string(&row.document_fk_id),
            ],
        ));
    }

    out.push_str("\n-- ownerships\n");
    for row in &dump.ownerships {
        out.push_str(&insert(
            "ownerships",
            "id, created, owner_id, owner_type, ownership_type, object_id, object_type",
            &[
                sql_string(&row.id),
                sql_string(&row.created),
                sql_string(&row.owner_id),
                sql_string(row.owner_type.as_sql_literal()),
                sql_string(row.ownership_type.as_sql_literal()),
                sql_string(&row.object_id),
                sql_string(row.object_type.as_sql_literal()),
            ],
        ));
    }

    out.push_str("\n-- relations\n");
    for row in &dump.relations {
        out.push_str(&insert(
            "relations",
            "id, created, relates_to, object_id, object_type",
            &[
                sql_string(&row.id),
                sql_string(&row.created),
                sql_string(&row.relates_to),
                sql_string(&row.object_id),
                sql_string(row.object_type.as_sql_literal()),
            ],
        ));
    }

    out.push_str("\nCOMMIT;\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plain_values_need_no_escape_literal() {
        assert_eq!(sql_string("hello"), "'hello'");
    }

    #[test]
    fn single_quotes_are_doubled() {
        assert_eq!(sql_string("O'Brien"), "'O''Brien'");
    }

    #[test]
    fn control_characters_use_an_escape_string_literal() {
        assert_eq!(sql_string("a\nb"), "e'a\\nb'");
        assert_eq!(sql_string("a\tb"), "e'a\\tb'");
        assert_eq!(sql_string("a\\b"), "e'a\\\\b'");
        assert_eq!(sql_string("a\rb"), "e'a\\rb'");
    }

    #[test]
    fn content_with_a_real_newline_stays_on_a_single_output_line() {
        // The escape-string form writes a literal backslash-n, not a real
        // newline byte, so a value containing one still keeps its own
        // `INSERT` on a single physical line of the emitted script.
        let mut dump = Dump::default();
        dump.assets.push(crate::rows::AssetRow {
            id: "id-1".to_owned(),
            created: "1970-01-01 00:00:00.000".to_owned(),
            asset_id: "asset-1".to_owned(),
            asset_type: u2s_redacto::model::AssetKind::Text,
        });
        dump.asset_versions.push(crate::rows::AssetVersionRow {
            id: "av-1".to_owned(),
            created: "1970-01-01 00:00:00.000".to_owned(),
            language: "en".to_owned(),
            version: 1,
            status: u2s_redacto::model::Status::Draft,
            content: "line one\nline two".to_owned(),
            asset_fk_id: "id-1".to_owned(),
        });
        let sql = to_sql(&dump);
        let insert_lines: Vec<&str> = sql
            .lines()
            .filter(|line| line.starts_with("INSERT INTO app_redacto.asset_version"))
            .collect();
        assert_eq!(insert_lines.len(), 1);
        assert!(insert_lines[0].contains("line one\\nline two"));
    }
}
