#!/usr/bin/env bash
# Pin the u2s crates to a revision of ajila-forms-conversion-engine-v3 and
# re-vendor them into vendor/crates, then copy the non-crate assets this repo
# takes from the same revision (the AEM and Redacto docker notes and scripts).
#
#   scripts/sync-u2s.sh ../unstructured-to-structured [rev]   # rev: default HEAD
#
# See u2s/VENDORED.md. Only the u2s crates are vendored; crates.io stays
# online. The revision must be on the remote, or nobody else could fetch it.
set -euo pipefail

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
  echo "usage: $0 <path-to-v3-checkout> [rev]" >&2
  exit 2
fi

SRC="$(cd "$1" && pwd)"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REV="$(git -C "$SRC" rev-parse "${2:-HEAD}^{commit}")"

# What this repo takes from upstream besides the crates.
ASSETS=(docker/aem/README.md docker/aem/bake-ubs-platform.sh docker/aem/dompurify docker/redacto/README.md)

if [ -z "$(git -C "$SRC" branch -r --contains "$REV")" ]; then
  echo "$REV is on no remote branch of $SRC: push it first" >&2
  exit 1
fi
if [ -n "$(git -C "$ROOT" status --porcelain -- Cargo.toml Cargo.lock .cargo vendor/crates "${ASSETS[@]}")" ]; then
  echo "the files this script rewrites have uncommitted changes; commit or stash them first" >&2
  exit 1
fi

cd "$ROOT"

# The git URL every u2s dependency in Cargo.toml names; they must agree.
URLS="$(sed -n -E 's/^u2s-[a-z0-9-]+ = \{ git = "([^"]+)", rev = "[0-9a-f]+" \}$/\1/p' Cargo.toml | sort -u)"
if [ "$(echo "$URLS" | grep -c .)" -ne 1 ]; then
  echo "expected one u2s git URL in Cargo.toml, found: ${URLS:-none}" >&2
  exit 1
fi
URL="$URLS"

# 1. Pin.
sed -i.bak -E "s/^(u2s-[a-z0-9-]+ = \{ git = \"[^\"]+\", rev = \")[0-9a-f]+(\" \})$/\1$REV\2/" Cargo.toml
rm -f Cargo.toml.bak

# 2. Re-vendor. `cargo vendor` vendors every source; keep only the u2s crates,
# the packages of the one git source. It also moves Cargo.lock to the new rev.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cargo vendor --quiet "$TMP/vendor" > /dev/null
rm -rf vendor/crates
mkdir -p vendor/crates
mv "$TMP"/vendor/u2s-* vendor/crates/

# 3. Point cargo at vendor/crates for that source. The source key carries the
# rev, so this file changes with every pin.
mkdir -p .cargo
cat > .cargo/config.toml <<EOF
# Generated by scripts/sync-u2s.sh; see u2s/VENDORED.md.

[net]
# Fetching the u2s git dependency, which only re-vendoring does, goes over SSH
# with your own git setup; cargo's built-in git client does not use it.
git-fetch-with-cli = true

# Builds take the u2s crates from vendor/crates and never fetch them. crates.io
# is not replaced.
[source."git+$URL?rev=$REV"]
git = "$URL"
rev = "$REV"
replace-with = "vendored-u2s"

[source.vendored-u2s]
directory = "vendor/crates"
EOF

# 4. The non-crate assets, from the same revision rather than the working tree.
rm -rf "${ASSETS[@]}"
git -C "$SRC" archive "$REV" "${ASSETS[@]}" | tar -x -C "$ROOT"

sed -i.bak "s/^Upstream commit: .*/Upstream commit: \`$REV\`/" u2s/VENDORED.md
rm -f u2s/VENDORED.md.bak

# Without network access to the u2s repository: proves vendor/crates is
# complete before anything is committed.
cargo build --locked --workspace --quiet
echo "pinned u2s to $REV. Next: cargo test --release --workspace."
git status --short -- Cargo.toml Cargo.lock .cargo vendor/crates "${ASSETS[@]}" u2s
