//! Black-box end-to-end: spawn the built binary and speak real MCP over stdio.
//!
//! Unlike the render servers, this one needs no fonts and no pdfium — it
//! never lays anything out — so every test here runs unconditionally, with no
//! machine-dependent skip gate.
//!
//! Fixtures are the synthetic XFA already generated by `u2s-render-xfa`'s own
//! test suite; this crate does not duplicate them.

use std::path::{Path, PathBuf};

use harness::{ErrorCase, ServerUnderTest, call, error_text, structured};
use serde_json::json;
use u2s_render_test_harness as harness;

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../u2s-render-xfa/fixtures/generated")
        .canonicalize()
        .expect("fixtures missing — run `cargo test -p u2s-render-xfa` first to generate them")
}

fn fixture(name: &str) -> String {
    fixtures().join(name).display().to_string()
}

fn server() -> ServerUnderTest {
    ServerUnderTest::locate("u2s-xfa-mcp", "xfa")
}

// ------------------------------------------------- shared contract battery

#[tokio::test]
async fn handshake_and_manifest_agree() {
    harness::handshake_matches_manifest(&server(), &fixtures()).await;
}

#[tokio::test]
async fn failures_are_tool_errors_and_the_session_survives() {
    let plain = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../u2s-render-pdf/fixtures/generated/ten-pages.pdf");
    let mut cases = vec![
        ErrorCase::new(
            "xfa_packets",
            json!({ "doc_path": "/nope/missing.pdf" }),
            &["/nope/missing.pdf"],
        ),
        ErrorCase::new(
            "xfa_read",
            json!({ "doc_path": fixture("minimal.xfa.pdf"), "packet": "no-such-packet" }),
            &["no-such-packet", "xfa_packets"],
        ),
        ErrorCase::new(
            "xfa_node",
            json!({ "doc_path": fixture("minimal.xfa.pdf"), "path": "does.not.exist" }),
            &["does.not.exist", "xfa_outline"],
        ),
        ErrorCase::new(
            "xfa_search",
            json!({ "doc_path": fixture("minimal.xfa.pdf"), "query": "(unclosed", "regex": true }),
            &["invalid regex"],
        ),
        ErrorCase::new("xfa_read", json!({}), &["doc_path"]),
    ];
    // The routing mirror: a plain PDF with no /XFA at all.
    if plain.exists() {
        cases.push(ErrorCase::new(
            "xfa_packets",
            json!({ "doc_path": plain.display().to_string() }),
            &["not an XFA form"],
        ));
    } else {
        eprintln!("note: skipping the plain-PDF case — run `cargo test -p u2s-render-pdf` first");
    }

    harness::errors_are_tool_errors(
        &server(),
        &cases,
        (
            "xfa_packets".to_string(),
            json!({ "doc_path": fixture("minimal.xfa.pdf") }),
        ),
    )
    .await;
}

#[tokio::test]
async fn the_same_outline_is_identical_across_processes() {
    // No image bytes here, so this is a direct structured-JSON comparison
    // rather than the render servers' pixel-digest helper.
    let args = json!({ "doc_path": fixture("minimal.xfa.pdf") });
    let mut runs = Vec::new();
    for _ in 0..2 {
        let client = server().connect().await;
        let result = call(&client, "xfa_outline", args.clone()).await;
        runs.push(structured(&result).clone());
        client.cancel().await.ok();
    }
    assert_eq!(
        runs[0], runs[1],
        "the same document must outline identically across separate processes"
    );
}

// ------------------------------------------------------ XFA-specific tests

#[tokio::test]
async fn xfa_packets_lists_the_template_packet() {
    let c = server().connect().await;
    let r = call(
        &c,
        "xfa_packets",
        json!({ "doc_path": fixture("minimal.xfa.pdf") }),
    )
    .await;
    let s = structured(&r);
    assert_eq!(s["count"], 1);
    let packets = s["packets"].as_array().unwrap();
    assert_eq!(packets.len(), 1);
    assert_eq!(packets[0]["name"], "template");
    assert!(packets[0]["byte_len"].as_u64().unwrap() > 0);
    c.cancel().await.ok();
}

#[tokio::test]
async fn xfa_read_windows_by_character_offset_and_reports_truncation() {
    let c = server().connect().await;

    let full = call(
        &c,
        "xfa_read",
        json!({ "doc_path": fixture("minimal.xfa.pdf"), "limit": 1_000_000 }),
    )
    .await;
    let sf = structured(&full);
    assert_eq!(sf["packet"], "template");
    assert!(!sf["truncated"].as_bool().unwrap());
    let total = sf["total_chars"].as_u64().unwrap();
    assert!(total > 100, "the fixture template is not that short");

    let windowed = call(
        &c,
        "xfa_read",
        json!({ "doc_path": fixture("minimal.xfa.pdf"), "offset": 0, "limit": 10 }),
    )
    .await;
    let sw = structured(&windowed);
    assert_eq!(sw["text"].as_str().unwrap().chars().count(), 10);
    assert!(sw["truncated"].as_bool().unwrap());
    assert_eq!(sw["total_chars"], total);

    // The window must be an exact prefix of the full text.
    assert_eq!(
        sw["text"],
        sf["text"]
            .as_str()
            .unwrap()
            .chars()
            .take(10)
            .collect::<String>()
    );

    c.cancel().await.ok();
}

#[tokio::test]
async fn xfa_search_finds_a_known_value_with_offset_and_context() {
    let c = server().connect().await;
    let r = call(
        &c,
        "xfa_search",
        json!({ "doc_path": fixture("minimal.xfa.pdf"), "query": "Ada" }),
    )
    .await;
    let s = structured(&r);
    assert_eq!(s["total_matches"], 1);
    assert!(!s["truncated"].as_bool().unwrap());
    let matches = s["matches"].as_array().unwrap();
    assert_eq!(matches.len(), 1);
    assert_eq!(matches[0]["packet"], "template");
    assert!(matches[0]["context"].as_str().unwrap().contains("Ada"));

    // The offset contract, asserted by composition rather than by number: a
    // hit's offset and length, handed straight to `xfa_read`, must return the
    // match. This is what the predecessor could not do — it reported byte
    // offsets found in a lowercased copy, while `xfa_read` windows by
    // character. Asserting the composition rather than a literal offset is
    // deliberate: every fixture here is ASCII, so a number cannot tell a
    // character offset from a byte one, but the composition holds on any input.
    let read = call(
        &c,
        "xfa_read",
        json!({
            "doc_path": fixture("minimal.xfa.pdf"),
            "packet": "template",
            "offset": matches[0]["offset"],
            "limit": matches[0]["length"],
        }),
    )
    .await;
    assert_eq!(
        structured(&read)["text"],
        "Ada",
        "a search offset must address the match in xfa_read's own coordinates"
    );

    c.cancel().await.ok();
}

/// An empty query is refused rather than answered. Compiled as a pattern it
/// would match at every position and report one hit per character.
#[tokio::test]
async fn xfa_search_refuses_a_query_that_would_match_everywhere() {
    let c = server().connect().await;
    for query in ["", "a*"] {
        let r = call(
            &c,
            "xfa_search",
            json!({ "doc_path": fixture("minimal.xfa.pdf"), "query": query, "regex": !query.is_empty() }),
        )
        .await;
        assert_eq!(r.is_error, Some(true), "query {query:?} should be refused");
        let msg = error_text(&r);
        assert!(msg.contains("empty string"), "query {query:?}: {msg}");
    }
    c.cancel().await.ok();
}

#[tokio::test]
async fn xfa_search_on_a_missing_packet_names_the_known_ones() {
    let c = server().connect().await;
    let r = call(
        &c,
        "xfa_search",
        json!({ "doc_path": fixture("minimal.xfa.pdf"), "query": "Ada", "packet": "datasets" }),
    )
    .await;
    assert_eq!(r.is_error, Some(true));
    let msg = error_text(&r);
    assert!(
        msg.contains("datasets") && msg.contains("template"),
        "{msg}"
    );
    c.cancel().await.ok();
}

#[tokio::test]
async fn xfa_outline_lists_the_fixtures_named_nodes() {
    let c = server().connect().await;
    let r = call(
        &c,
        "xfa_outline",
        json!({ "doc_path": fixture("minimal.xfa.pdf") }),
    )
    .await;
    let s = structured(&r);
    assert!(!s["truncated"].as_bool().unwrap());
    let paths: Vec<&str> = s["entries"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| e["path"].as_str().unwrap())
        .collect();
    assert!(paths.iter().any(|p| p.ends_with("form1.Body.Title")));
    assert!(paths.iter().any(|p| p.ends_with("form1.Body.FirstName")));
    c.cancel().await.ok();
}

#[tokio::test]
async fn xfa_outline_reports_truncation_honestly_when_capped() {
    let c = server().connect().await;
    let r = call(
        &c,
        "xfa_outline",
        json!({ "doc_path": fixture("overflow.xfa.pdf"), "limit": 3 }),
    )
    .await;
    let s = structured(&r);
    assert!(s["truncated"].as_bool().unwrap());
    assert!(s["entries"].as_array().unwrap().len() <= 3);
    c.cancel().await.ok();
}

#[tokio::test]
async fn xfa_node_resolves_a_path_returned_by_outline_and_shows_only_immediate_children() {
    let c = server().connect().await;

    let outline = call(
        &c,
        "xfa_outline",
        json!({ "doc_path": fixture("minimal.xfa.pdf") }),
    )
    .await;
    let so = structured(&outline);
    let body_path = so["entries"]
        .as_array()
        .unwrap()
        .iter()
        .find(|e| e["path"].as_str().unwrap().ends_with("form1.Body"))
        .expect("outline must list Body")["path"]
        .as_str()
        .unwrap()
        .to_string();

    let node = call(
        &c,
        "xfa_node",
        json!({ "doc_path": fixture("minimal.xfa.pdf"), "path": body_path }),
    )
    .await;
    let sn = structured(&node);
    assert_eq!(sn["kind"], "subform");
    let children = sn["children"].as_array().unwrap();
    // Body has exactly two children: Title, FirstName — no grandchildren leak in.
    assert_eq!(children.len(), 2);
    assert!(
        children
            .iter()
            .any(|c| c["path"].as_str().unwrap().ends_with("Title"))
    );
    assert!(
        children
            .iter()
            .any(|c| c["path"].as_str().unwrap().ends_with("FirstName"))
    );

    c.cancel().await.ok();
}

#[tokio::test]
async fn a_plain_pdf_is_refused_and_names_pdf_info() {
    let plain = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../u2s-render-pdf/fixtures/generated/ten-pages.pdf");
    if !plain.exists() {
        eprintln!("skipping: run `cargo test -p u2s-render-pdf` first");
        return;
    }
    let c = server().connect().await;
    for tool in [
        "xfa_packets",
        "xfa_outline",
        "xfa_node",
        "xfa_read",
        "xfa_search",
    ] {
        let mut args = json!({ "doc_path": plain.display().to_string() });
        if tool == "xfa_node" {
            args["path"] = json!("template[0]");
        }
        if tool == "xfa_search" {
            args["query"] = json!("x");
        }
        let r = call(&c, tool, args).await;
        assert_eq!(r.is_error, Some(true), "{tool} should refuse a non-XFA PDF");
        assert!(
            error_text(&r).contains("not an XFA form"),
            "{tool}: {}",
            error_text(&r)
        );
    }
    let alive = call(
        &c,
        "xfa_packets",
        json!({ "doc_path": fixture("minimal.xfa.pdf") }),
    )
    .await;
    assert_ne!(
        alive.is_error,
        Some(true),
        "session must survive the errors"
    );
    c.cancel().await.ok();
}
